#!/bin/bash

#gcloud.sh is a tool to start/stop a VM under the 'name-of-project' in GCP
#args [start|stop]
#run by issuing,
#sh gcloud.sh start
gcloud compute instances $1 --zone "csi-4160-keijiroemmich" "csi4160-final-vm" --project "final-project" 
